apiVersion: v1
kind: page
spec:
  id: yhowudy
  title: Default page
  content:
    - component: Form
      name: form
      children:
        - component: DatePicker
          name: datePicker
        - component: Paper
          name: paper1
          children:
            - component: DataGrid
              name: dataGrid
        - component: Tabs
          name: tabs
        - component: Metric
          name: metric1
          props:
            numberFormat:
              kind: preset
              preset: bytes
    - component: Form
      name: form1
      children:
        - component: DatePicker
          name: datePicker1
        - component: Paper
          name: paper2
          children:
            - component: DataGrid
              name: dataGrid1
        - component: Metric
          name: metric2
          props:
            numberFormat:
              kind: preset
              preset: bytes
  display: shell
