export const standard = {
  documents: [
    {
      __typename: 'Document',
      id: 'doc-1',
      name: 'document:project-documentation',
      title: 'Project Documentation',
      type: 'document',
      access_role: 'Restricted',
      edit_role: 'Operator',
      created_at: '2024-10-01T10:00:00.000Z',
      updated_at: '2024-10-05T15:30:00.000Z',
      created_by: {
        __typename: 'User',
        id: 1,
        name: 'Admin User',
        email: 'adminuser@example.com',
      },
      updated_by: {
        __typename: 'User',
        id: 1,
        name: 'Admin User',
        email: 'adminuser@example.com',
      },
    },
    {
      __typename: 'Document',
      id: 'doc-2',
      name: 'wiki:team-handbook',
      title: 'Team Handbook',
      type: 'document',
      access_role: 'Operator',
      edit_role: 'Coordinator',
      created_at: '2024-09-15T08:00:00.000Z',
      updated_at: '2024-10-03T12:00:00.000Z',
      created_by: {
        __typename: 'User',
        id: 2,
        name: 'Coordinator User',
        email: 'coordinatoruser@example.com',
      },
      updated_by: {
        __typename: 'User',
        id: 2,
        name: 'Coordinator User',
        email: 'coordinatoruser@example.com',
      },
    },
    {
      __typename: 'Document',
      id: 'doc-3',
      name: 'note:meeting-notes-2024-10-07',
      title: 'Meeting Notes - Oct 7',
      type: 'document',
      access_role: 'Restricted',
      edit_role: 'Restricted',
      created_at: '2024-10-07T09:00:00.000Z',
      updated_at: '2024-10-07T09:30:00.000Z',
      created_by: {
        __typename: 'User',
        id: 3,
        name: 'Regular User',
        email: 'regularuser@example.com',
      },
      updated_by: {
        __typename: 'User',
        id: 3,
        name: 'Regular User',
        email: 'regularuser@example.com',
      },
    },
  ],
}
